(async () => {
  const express = require('express')
  const app = express()
  const examples = require('./controllers')
  const port = 3000
  const obj = [
    { id: 1, name: 'Saint seiya'},
    { id: 2, name: 'Naruto'},
    { id: 3,name: 'Nanatsu no Tazai'}
  ]

  app.get('/', (req, res) => {
    res.send('Hello World!')
  })

  console.log('                                                                              ')
  console.log('                                                                              ')
  console.log("JavaScript Ecma Script 6 :")
  console.log('------------------------------------------------------------------------------')
  await examples.es6.literal('Irza', 'Arivin')
  await examples.es6.arrayFunc()
  await examples.es6.destruct({nama: 'Irza', umur: 18, status: 'Mahasiswa'})
  await examples.es6.ternary(true)
  await examples.es6.map(obj)
  await examples.es6.filter(obj)
  await examples.es6.find(obj)
  await examples.es6.reduce(obj)
  await examples.es6.spread('Aku', 'Suka', 'Kamu')
  await examples.es6.defaultParams(1, 9)
  console.log('==============================================================================')
  console.log('                                                                              ')
  console.log('                                                                              ')
  console.log("LoDash Array :")
  console.log('------------------------------------------------------------------------------')
  await examples.lodash.array.chunk()
  await examples.lodash.array.compact()
  await examples.lodash.array.concat()
  await examples.lodash.array.difference()
  await examples.lodash.array.differenceBy()
  await examples.lodash.array.differenceWith()
  await examples.lodash.array.drop()
  await examples.lodash.array.dropRight()
  await examples.lodash.array.dropRightWhile()
  await examples.lodash.array.dropWhile()
  await examples.lodash.array.fill()
  await examples.lodash.array.findIndex()
  await examples.lodash.array.findLastIndex()
  await examples.lodash.array.head()
  await examples.lodash.array.flatten()
  await examples.lodash.array.flattenDeep()
  await examples.lodash.array.flattenDepth()
  await examples.lodash.array.fromPairs()
  await examples.lodash.array.indexOf()
  await examples.lodash.array.initial()
  await examples.lodash.array.intersection()
  await examples.lodash.array.intersectionBy()
  await examples.lodash.array.intersectionWith()
  await examples.lodash.array.join()
  await examples.lodash.array.last()
  await examples.lodash.array.lastIndexOf()
  await examples.lodash.array.nth()
  await examples.lodash.array.pull()
  await examples.lodash.array.pullAll()
  await examples.lodash.array.pullAllBy()
  await examples.lodash.array.pullAllWith()
  await examples.lodash.array.pullAt()
  await examples.lodash.array.reverse()
  await examples.lodash.array.remove()
  await examples.lodash.array.slice()
  await examples.lodash.array.sortedIndex()
  await examples.lodash.array.sortedIndexBy()
  await examples.lodash.array.sortedIndexOf()
  await examples.lodash.array.sortedLastIndex()
  await examples.lodash.array.sortedLastIndexBy()
  await examples.lodash.array.sortedLastIndexOf()
  await examples.lodash.array.sortedUniq()
  await examples.lodash.array.sortedUniqBy()
  await examples.lodash.array.tail()
  await examples.lodash.array.take()
  await examples.lodash.array.takeRight()
  await examples.lodash.array.takeRightWhile()
  await examples.lodash.array.takeWhile()
  await examples.lodash.array.union()
  await examples.lodash.array.unionBy()
  await examples.lodash.array.unionWith()
  await examples.lodash.array.uniq()
  await examples.lodash.array.uniqBy()
  await examples.lodash.array.uniqWith()
  await examples.lodash.array.unzip()
  await examples.lodash.array.unzipWith()
  await examples.lodash.array.without()
  await examples.lodash.array.xor()
  await examples.lodash.array.xorBy()
  await examples.lodash.array.xorWith()
  await examples.lodash.array.zip()
  await examples.lodash.array.zipObject()
  await examples.lodash.array.zipObjectDeep()
  await examples.lodash.array.zipWith()
  // await examples.lodash.assign({a: 1}, {b: 2})
  // await examples.lodash.times(7)
  // await examples.lodash.find([1, 2, 3, 4, 5])
  // await examples.lodash.filter([1, 2, 3, 4, 5])
  // await examples.lodash.get({ id: 3,name: 'Nanatsu no Tazai'})
  // await examples.lodash.set({ id: 3,name: 'Nanatsu no Tazai'})
  // await examples.lodash.keyBy(obj)
  // await examples.lodash.uniq([1, 2, 3, 3, 3, 4, 5, 6, 7, 8, 9])
  // await examples.lodash.difference()
  // await examples.lodash.intersection()
  // await examples.lodash.sortBy(obj)
  console.log('==============================================================================')
  console.log('                                                                              ')
  console.log('                                                                              ')
  console.log("LoDash Collection :")
  console.log('------------------------------------------------------------------------------')
  await examples.lodash.collection.countBy()
  await examples.lodash.collection.forEach()
  await examples.lodash.collection.forEachRight()
  await examples.lodash.collection.every()
  await examples.lodash.collection.filter()
  await examples.lodash.collection.find()
  await examples.lodash.collection.findLast()
  await examples.lodash.collection.flatMap()
  await examples.lodash.collection.flatMapDeep()
  await examples.lodash.collection.flatMapDepth()
  await examples.lodash.collection.groupBy()
  await examples.lodash.collection.includes()
  await examples.lodash.collection.invokeMap()
  await examples.lodash.collection.keyBy()
  await examples.lodash.collection.map()
  await examples.lodash.collection.orderBy()
  await examples.lodash.collection.partition()
  await examples.lodash.collection.reduce()
  await examples.lodash.collection.reduceRight()
  await examples.lodash.collection.reject()
  await examples.lodash.collection.sample()
  await examples.lodash.collection.sampleSize()
  await examples.lodash.collection.shuffle()
  await examples.lodash.collection.size()
  await examples.lodash.collection.some()
  await examples.lodash.collection.sortBy()
  console.log('==============================================================================')
  
  app.listen(port, () => {
    // console.log(`RND Lodash - ES6 listening on port ${port}`)
  })
})()